url: "https://www.vitormach.dev"
baseurl: "/"

# Site settings
title: Vitor Machado
author: Vitor Machado
email: vmachado@cos.ufrj.br
description: "Vitor Machado's personal homepage."
keywords: "tech,developer,software,work,academic,personal,blog"
image: "/favicon.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  background: fcfcfc
  navbar: eeeeee
  primary: 851e3e
  secondary: 651e3e
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: flickr
    url: https://www.flickr.com/photos/vitormach
    fa: fab fa-flickr
  - title: unsplash
    url: https://unsplash.com/@vitormach
    fa: fab fa-unsplash
  - title: instagram
    url: https://www.instagram.com/vitor.p.mach
    fa: fab fa-instagram
  - title: github
    url: https://github.com/vittau
    fa: fab fa-github
  - title: linkedin
    url: https://www.linkedin.com/in/vitormach
    fa: fab fa-linkedin
  - title: twitter
    url: https://twitter.com/VittauMach
    fa: fab fa-twitter

# Build settings
markdown: kramdown
permalink: pretty
