# Site settings
title: Vitor Machado's blog
subtitle: "Ramblings of a software developer"
email: vmachado@cos.ufrj.br
description: "IT Guy"
baseurl: "http://www.vitormachado.me/blog"
url: "http://www.vitormachado.me/blog"
twitter_username: "VittauMach"
github_username:  "vittau"
instagram_username: "vitor.p.mach"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed